### ISSUE TITLE
Missing word-break inside file list columns

### ISSUE THREAD

**Issue by nopeslide** [Amonith/mattermost-file-list#25]
When I open the modal on my server, I see something like this:
![files](https://user-images.githubusercontent.com/42803409/80213819-0ba7e880-863a-11ea-9719-c2e316336c9e.png)
This rendering issue could be mitigated by allowing word-breaks not only for the links inside the filename column but also inside other columns:
```css
table.file-list-table td {
    word-break: break-word;
}
```
resulting in a better layout:
![files2](https://user-images.githubusercontent.com/42803409/80216433-53307380-863e-11ea-8c4d-bfe2cdd25d15.png)
